build:
    protoc --go_out=. --go-grpc_out=. \
        --go_opt=paths=source_relative \
        --go-grpc_opt=paths=source_relative \
        proto/valvota.proto

    go build -ldflags="-s -w" -trimpath -o bin/valvota ./cmd/valvota

debug:
    go build -o bin/valvota ./cmd/valvota

test:
    go test -v ./...
